# Generated by Django 6.0.2 on 2026-02-25 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('registration_no', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('gas_level', models.IntegerField()),
                ('smoke_level', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('alert_message', models.TextField()),
                ('alert_time', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.vehicle')),
            ],
        ),
    ]
